from sqlalchemy import ForeignKey, Column, Integer, DateTime, String, Float
from database import Base


class Contract(Base):
    __tablename__ = "contracts"

    id = Column(Integer, primary_key=True, index=True)
    attorney_id = Column(Integer, ForeignKey("attorneys.id"))
    client_id = Column(Integer, ForeignKey("clients.id"))
    property_id = Column(Integer, ForeignKey("properties.id"))
    agents_id = Column(Integer, ForeignKey("agents.id"))
    mortgage_applicaton_date = Column(DateTime)
    buyer_or_seller = Column(String)
    purchase_price = Column(Float)
    concessions = Column(Float)
    contract_date = Column(DateTime)
    contract_of_sale_sent = Column(DateTime)
    attorney_approval_seller = Column(DateTime)
    attorney_approval_buyer = Column(DateTime)
    deposit_received = Column(DateTime)
    deal_sheet =  Column(DateTime)
    sold_rider =  Column(DateTime)
    appraisal_date =  Column(DateTime)
    mortgage_commitment_contract =  Column(DateTime)
    mortgage_commitment_actual =  Column(DateTime)
    clear_to_closed = Column(DateTime)
    rate_lock_expiration = Column(DateTime)
    utility_email = Column(DateTime)
    fwt = Column(DateTime)
    close_date_contract = Column(DateTime)
    close_date_actual = Column(DateTime)
    updated_coi = Column(DateTime)
    pickup_sign = Column(DateTime)
    pickup_lockbox = Column(DateTime)
    zillow_email1 = Column(String)
    zillow_email2 = Column(String)
    zillow_past_sale = Column(DateTime)
    case_closed = Column(DateTime)
    postcards_just_listed = Column(DateTime)
    postcards_just_sold = Column(DateTime)